name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure pnpm store path
        run: pnpm config set store-dir ~/.pnpm-store

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            pnpm install --no-frozen-lockfile
          fi

      - name: Lint
        run: pnpm lint

      - name: Test (exclude e2e)
        run: pnpm -r --if-present --filter "!@ja-to-en/e2e" run test

      - name: Build
        run: pnpm build

      - name: Package extension artifact
        run: |
          cd packages/background/dist
          zip -r ../../../../extension.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-dist
          path: extension.zip

  # E2E job intentionally omitted in translation MVP PR. CI for E2E hardening
  # remains in PR #4. This job will be reintroduced when E2E is stabilized.
